# Generated by Django 5.1.3 on 2024-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('access_to_electricity', models.FloatField(blank=True, null=True)),
                ('access_to_clean_fuels', models.FloatField(blank=True, null=True)),
                ('renewable_electricity_capacity', models.FloatField(blank=True, null=True)),
                ('financial_flows', models.BigIntegerField(blank=True, null=True)),
                ('renewable_energy_share', models.FloatField(blank=True, null=True)),
                ('electricity_from_fossil_fuels', models.FloatField(blank=True, null=True)),
                ('electricity_from_nuclear', models.FloatField(blank=True, null=True)),
                ('electricity_from_renewables', models.FloatField(blank=True, null=True)),
                ('low_carbon_electricity', models.FloatField(blank=True, null=True)),
                ('primary_energy_consumption', models.FloatField(blank=True, null=True)),
                ('energy_intensity', models.FloatField(blank=True, null=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('renewables_equivalent', models.FloatField(blank=True, null=True)),
                ('gdp_growth', models.FloatField(blank=True, null=True)),
                ('gdp_per_capita', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
